
class Msg:
    AtAll = "AtAll"  # 艾特全体成员
    AtUin = "AtUin"  # 被艾特账号
    AtName = "AtName"  # 被艾特昵称
    Id = "Id"  # ID
    Ok = "Ok"  # 状态码
    No = "No"  # 状态码
    Op = "Op"  # 操作
    OpUid = "OpUid"  # 操作
    All = "All"  # 所有
    Get = "Get"  # 得到
    Gif = "Gif"  # 动图
    Img = "Img"  # 图片
    Ptt = "Ptt"  # 语音
    Uid = "Uid"  # 账号
    Uin = "Uin"  # 账号
    Url = "Url"  # 链接
    Xml = "Xml"  # XML
    Code = "Code"  # 码
    Info = "Info"  # 信息
    Json = "Json"  # JSON
    Text = "Text"  # 文本消息
    Temp = "Temp"  # 临时消息
    Time = "Time"  # 时间
    Type = "Type"  # 类型
    Emoid = "Emoid"  # 表情id
    Flash = "Flash"  # 闪图
    MsgId = "MsgId"  # 消息id
    Reply = "Reply"  # 回复
    Title = "Title"  # 用户头衔
    Value = "Value"  # 值
    Audio = "Audio"  # 音频
    Video = "Video"  # 视频
    Width = "Width"  # 宽度
    Bubble = "Bubble"  # 气泡id
    Height = "Height"  # 高度
    Notice = "Notice"  # 公告
    People = "People"  # 人数
    Refresh = "Refresh"  # 刷新
    UinName = "UinName"  # 名称 备注.....
    UinNick = "UinNick"  # 昵称
    Typeface = "Typeface"  # 字体
    Withdraw = "Withdraw"  # 撤回
    OpName = "OpName"  # 操作者名字
    OpNick = "OpNick"  # 操作者昵称
    Agree = "Agree"  # 同意
    Refuse = "Refuse"  # 拒绝
    Ignore = "Ignore"  # 忽略
    Account = "Account"  # 登录账号
    Open = "Open"  # 打开
    Close = "Close"  # 关闭
    MD5 = "MD5"  # MD5
    Size = "Size"  # 大小
    Offset = "Offset"  # 开始
    Add = "Add"  # 增加
    Remove = "Remove"  # 移除
    Seq = "Seq"  # 序号
    Cmd = "Cmd"
    Dat = "Dat"
    ProgressPush = "ProgressPush"  # 进度推送
    PokeID = "PokeID"  # 戳一戳id
    PokeIDSub = "PokeIDSub"  # 戳一戳子id
    PokeMsg = "PokeMsg"  # 戳一戳消息
    PokeSize = "PokeSize"  # 戳一戳大小
    Dice = "Dice"  # 骰子
    WindowJitter = "WindowJitter"  # 窗口抖动
    FlashWord = "FlashWord"  # 闪字
    FingerGuess = "FingerGuess"  # 猜拳
    HeadPortrait = "HeadPortrait"  # 头像
    AppId = "AppId"  # 账号
    Emoy = "Emoy"  # 小黄脸表情
    Emoq = "Emoq"  # 超级表情
    EmoReply = "EmoReply"  # 表情回应
    RedPacket = "RedPacket"
    TransferMoney = "TransferMoney"
    GrayTip = "GrayTip"
    SecSession = "SecSession"
    InstantAction = "InstantAction"
    SelfTouch = "SelfTouch"
    Ark = "Ark"
    Embed = "Embed"
    Markdown = "Markdown"
    Keyboard = "Keyboard"
    File = "File"
    Unknown = "Unknown"
    Permission = "Permission"
    BlackList = "BlackList"
    Profile = "Profile"
    Skey = "Skey"  # Skey   pskey在用户信息获取
    Age = "Age"  # 年龄
    Gender = "Gender"  # 性别
    Nick = "Nick"  # 昵称
    Name = "Name"  # 备注
    JoinTime = "JoinTime"  # 加入时间
    LastSpeakTime = "LastSpeakTime"  # 最后发言时间
    Level = "Level"  # 等级
    Location = "Location"  # 地区
    System = "System"  # 系统消息
    Online = "Online"  # 查询在线状态
    Goline = "Goline"  # 账号上线
    GolineRetry = "GolineRetry"  # 重新上线
    Offline = "Offline"  # 账号下线
    Heartbeat = "Heartbeat"  # 心跳消息
    OntimeTask = "OntimeTask"  # 整点任务
    GolineMode = "GolineMode"  # 上线模式
    CallbackMode = "CallbackMode"  # 上线模式
    Mail = "Mail"  # 上线模式
    Qzone = "Qzone"  # 空间消息
    Debug = "Debug"  # 调试模式
    CacheNewFile = "CacheNewFile"
    Unauthorized = "Unauthorized"  # 未授权
    WebScanCodeLogin = "WebScanCodeLogin"  # 网站扫码登录

    MultiMsg = "MultiMsg"  # 消息合并转发
    MultiMsgGet = "MultiMsgGet"  # 消息合并转发 获取
    MultiMsgPut = "MultiMsgPut"  # 消息合并转发 保存

    Friend = "Friend"  # 好友消息
    FriendListDisable = "FriendListDisable"  # 好友禁用列表
    FriendListGet = "FriendListGet"  # 获取好友列表
    FriendBeatABeat = "FriendBeatABeat"  # 好友拍一拍
    FriendMsgCacheGet = "FriendMsgCacheGet"  # 获取好友消息缓存
    FriendNotify = "FriendNotify"  # 新朋友通知

    Group = "Group"  # 群聊消息
    Owner = "Owner"  # 群主/频道主 QQ
    GroupId = "GroupId"  # 群号
    GroupName = "GroupName"  # 群名
    GroupListDisable = "GroupListDisable"  # 群聊禁用列表
    GroupListGet = "GroupListGet"  # 获取群聊列表
    GroupListGetName = "GroupListGetName"  # 获取群聊名称
    GroupMemberListGet = "GroupMemberListGet"  # 获取群聊成员列表
    GroupMemberListGetAdmin = "GroupMemberListGetAdmin"  # 获取群聊管理员列表
    GroupMemberListGetInactive = "GroupMemberListGetInactive"  # 获取群聊成员不活跃列表
    GroupMemberListGetProhibit = "GroupMemberListGetProhibit"  # 获取群聊成员被禁言列表
    GroupMemberListGetInfo = "GroupMemberListGetInfo"  # 获取群聊成员信息
    GroupMemberJoin = "GroupMemberJoin"  # 群聊成员加入
    GroupMemberExit = "GroupMemberExit"  # 群聊成员退出
    GroupMemberNickModify = "GroupMemberNickModify"  # 修改群聊成员昵称
    GroupMemberInvitation = "GroupMemberInvitation"  # 邀请 好友 进群
    GroupModifyAdmin = "GroupModifyAdmin"  # 群聊管理员修改
    GroupModifySpecialTitle = "GroupModifySpecialTitle"  # 修改群聊专属头衔
    GroupNotify = "GroupNotify"  # 群通知
    GroupProhibit = "GroupProhibit"  # 群聊禁言
    GroupMsgCacheGet = "GroupMsgCacheGet"  # 获取群聊消息缓存
    GroupMsgAnonymous = "GroupMsgAnonymous"  # 群聊消息匿名
    GroupAnonymous = "GroupAnonymous"  # 群聊匿名开关变动
    GroupMusic = "GroupMusic"  # 一起听歌开关变动
    GroupBeatABeat = "GroupBeatABeat"  # 群聊拍一拍
    GroupEssence = "GroupEssence"  # 群聊精华
    GroupDissolut = "GroupDissolut"  # 群聊解散
    GroupClockin = "GroupClockin"  # 群聊打卡

    GroupFile = "GroupFile"  # 群文件
    GroupFileListGet = "GroupFileListGet"  # 获取列表
    GroupFileUpload = "GroupFileUpload"  # 上传文件
    GroupFileCreate = "GroupFileCreate"  # 创建文件夹
    GroupFileRemove = "GroupFileRemove"  # 删除文件
    GroupFileRemoveFolder = "GroupFileRemoveFolder"  # 删除文件夹
    GroupFileMove = "GroupFileMove"  # 移动文件
    GroupFileRename = "GroupFileRename"  # 重命名文件夹

    Guild = "Guild"  # 频道消息
    TinyId = "TinyId"
    GuildId = "GuildId"  # 频道 id
    GuildCode = "GuildCode"  # 频道 id 号
    ChannelId = "ChannelId"  # 频道 id 子
    GuildType = "GuildType"  # 频道 type
    GuildName = "GuildName"  # 频道名
    ChannelName = "ChannelName"  # 频道名 子
    GuildMsgCacheGet = "GuildMsgCacheGet"  # 获取频道消息缓存
    GuildMemberExit = "GuildMemberExit"  # 频道成员退出
    GuildEssence = "GuildEssence"  # 频道精华

    FavoriteCard = "FavoriteCard"  # 名片赞
    FavoriteCardListGet = "FavoriteCardListGet"  # 名片赞列表获取

    UserInfoGet = "UserInfoGet"  # 获取上线信息
    UserInfoModify = "UserInfoModify"  # 修改用户信息 可携带 Nick Gender ...
    UserJoinGroup = "UserJoinGroup"  # 加群
    UserExitGroup = "UserExitGroup"  # 退群
    UserAddFriend = "UserAddFriend"  # 加好友
    UserDelFriend = "UserDelFriend"  # 删除好友

    CustomJson = "CustomJson"  # 自定义JSON消息
    JSON_KG = "JSON_KG"  # 酷狗音乐 分享/音乐播放
    JSON_WY = "JSON_WY"  # 网易云音乐 分享/音乐播放
    JSON_QQ = "JSON_QQ"  # QQ音乐 分享/音乐播放
    JSON_KW = "JSON_KW"  # 酷我音乐 分享/音乐播放
    JSON_JSHU = "JSON_JSHU"  # 简书 分享/音乐播放
    JSON_BAIDU = "JSON_BAIDU"  # 百度 分享/音乐播放
    JSON_YK = "JSON_YK"  # 优酷 分享/音乐播放
    JSON_IQY = "JSON_IQY"  # 爱奇艺 分享/音乐播放
    JSON_BD = "JSON_BD"  # 波点 分享/音乐播放
    JSON_BL = "JSON_BL"  # 哔哩哔哩 分享/音乐播放
    JSON_KS = "JSON_KS"  # 快手 分享/音乐播放
    JSON_MG = "JSON_MG"  # 咪咕 分享/音乐播放
    JSON_QQLLQ = "JSON_QQLLQ"  # QQ浏览器 分享/音乐播放
    JSON_QQKJ = "JSON_QQKJ"  # QQ空间 分享/音乐播放
    JSON_5SING = "JSON_5SING"  # 5SING 分享/音乐播放

    PrintR = "PrintR"  # 打印日志
    PrintG = "PrintG"  # 打印日志
    PrintB = "PrintB"  # 打印日志
    PrintY = "PrintY"  # 打印日志
    PrintW = "PrintW"  # 打印日志

    GM_PO = "PO"  # 上线类型   官方人机
    GM_PA = "PA"  # 上线类型   安卓手机
    GM_PP = "PP"  # 上线类型   安卓平板
    GM_PL = "PL"  # 上线类型   企鹅密码
    GM_SA = "SA"  # 上线类型   安卓手表 (扫码登陆)
    GM_SL = "SL"  # 上线类型   企鹅扫码 (扫码登陆)

    CM_WH = "WH"  # 官方人机 回调模式 WebHook
    CM_WS = "WS"  # 官方人机 回调模式 WebSocket
